# Generated by Django 4.2.16 on 2024-12-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.IntegerField(db_column='appointmentID', primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField(blank=True, db_column='appointmentDate', null=True)),
                ('appointmenttime', models.TimeField(blank=True, db_column='appointmentTime', null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bankid', models.CharField(db_column='bankID', max_length=3, primary_key=True, serialize=False)),
                ('bankname', models.CharField(blank=True, db_column='bankName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billid', models.IntegerField(db_column='billID', primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('createddate', models.DateField(blank=True, db_column='createdDate', null=True)),
                ('paymentstatus', models.IntegerField(blank=True, db_column='paymentStatus', null=True)),
                ('paiddate', models.DateField(blank=True, db_column='paidDate', null=True)),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('cashierid', models.CharField(db_column='cashierID', max_length=3, primary_key=True, serialize=False)),
                ('cashiername', models.CharField(blank=True, db_column='cashierName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'cash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.CharField(db_column='departmentID', max_length=2, primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, db_column='departmentName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('ewalletid', models.CharField(db_column='ewalletID', max_length=3, primary_key=True, serialize=False)),
                ('ewalletname', models.CharField(blank=True, db_column='ewalletName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ewallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('staffid', models.CharField(db_column='staffID', max_length=7, primary_key=True, serialize=False)),
                ('staffssn', models.CharField(db_column='staffSSN', max_length=10, unique=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=20)),
                ('midname', models.CharField(blank=True, db_column='midName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=20, null=True)),
                ('staffdob', models.DateField(blank=True, db_column='staffDoB', null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=10, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medical_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineid', models.CharField(db_column='medicineID', max_length=11, primary_key=True, serialize=False)),
                ('medicinename', models.CharField(blank=True, db_column='medicineName', max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(db_column='patientID', max_length=7, primary_key=True, serialize=False)),
                ('patientssn', models.CharField(db_column='patientSSN', max_length=10, unique=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=20)),
                ('midname', models.CharField(blank=True, db_column='midName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=20, null=True)),
                ('patientdob', models.DateField(blank=True, db_column='patientDoB', null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentApproach',
            fields=[
                ('paid', models.CharField(db_column='PAID', max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'payment_approach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacyid', models.CharField(db_column='pharmacyID', max_length=2, primary_key=True, serialize=False)),
                ('pharmacyname', models.CharField(blank=True, db_column='pharmacyName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.CharField(db_column='roomID', max_length=3, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('roomtype', models.CharField(blank=True, db_column='roomType', max_length=20, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentid', models.IntegerField(db_column='treatmentID', primary_key=True, serialize=False)),
                ('treatmentdate', models.DateField(blank=True, db_column='treatmentDate', null=True)),
                ('treatmentprocedure', models.CharField(blank=True, db_column='treatmentProcedure', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'treatment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmittedTo',
            fields=[
                ('patientid', models.OneToOneField(db_column='patientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.patient')),
                ('admitteddate', models.DateField(blank=True, db_column='admittedDate', null=True)),
                ('dischargeddate', models.DateField(blank=True, db_column='dischargedDate', null=True)),
            ],
            options={
                'db_table': 'admitted_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorid', models.OneToOneField(db_column='doctorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.medicalstaff')),
                ('license', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('departmentid', models.OneToOneField(db_column='departmentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.department')),
                ('startdate', models.DateField(db_column='startDate')),
            ],
            options={
                'db_table': 'manages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('recordid', models.IntegerField(db_column='recordID')),
                ('patientid', models.OneToOneField(db_column='patientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.patient')),
                ('recorddate', models.DateField(blank=True, db_column='recordDate', null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=1000, null=True)),
                ('testresult', models.CharField(blank=True, db_column='testResult', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'medical_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurseid', models.OneToOneField(db_column='nurseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.medicalstaff')),
                ('yearexperience', models.IntegerField(blank=True, db_column='yearExperience', null=True)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsFamily',
            fields=[
                ('familyid', models.IntegerField(db_column='familyID')),
                ('patientid', models.OneToOneField(db_column='patientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.patient')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=10, null=True)),
            ],
            options={
                'db_table': 'patients_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescribes',
            fields=[
                ('patientid', models.OneToOneField(db_column='patientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.patient')),
                ('prescribesdate', models.DateField(blank=True, db_column='prescribesDate', null=True)),
            ],
            options={
                'db_table': 'prescribes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assists',
            fields=[
                ('nurseid', models.OneToOneField(db_column='nurseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.nurse')),
            ],
            options={
                'db_table': 'assists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('doctorid', models.OneToOneField(db_column='doctorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.doctor')),
            ],
            options={
                'db_table': 'performs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('doctorid', models.OneToOneField(db_column='doctorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.doctor')),
                ('aspecialization', models.CharField(db_column='aSpecialization', max_length=20)),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TakesCare',
            fields=[
                ('nurseid', models.OneToOneField(db_column='nurseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.nurse')),
            ],
            options={
                'db_table': 'takes_care',
                'managed': False,
            },
        ),
    ]
