# Generated by Django 4.2.16 on 2024-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentView',
            fields=[
                ('appointmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('appointment_date', models.DateTimeField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Appointment_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillView',
            fields=[
                ('billID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=255)),
                ('bill_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Bill_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordView',
            fields=[
                ('recordID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('doctor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Medical_Record_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsFamilyView',
            fields=[
                ('familyID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('family_member_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Patients_Family_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientView',
            fields=[
                ('patientID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Patient_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescribesView',
            fields=[
                ('prescriptionID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Prescribes_View',
                'managed': False,
            },
        ),
    ]
